spring.application.name=polaris
#---------------------
#Swagger configuration
#---------------------
info.name=polaris-service
info.description=Polaris service
info.version=1.0
info.contact.owner=IOTech
info.contact.email=hello@iotech.mn
springdoc.packagesToScan=mn.io.polaris.controller
#---------------------
#Server configuration
#---------------------
server.port=39083
server.servlet.context-path=/polaris
#----------------------
#Database configuration
#----------------------
spring.datasource.username=bgpay
# spring.datasource.password=BG@953#pglbs25$Bt
spring.datasource.password=BG@953#pglbs25$Bt
#spring.datasource.url=jdbc:postgresql://bgdb.bichilglobus.mn:5432/bichilglobus?currentSchema=bgpay
# spring.datasource.url=jdbc:postgresql://mstrdb.bichilglobus.mn:5432/bichilglobus?currentSchema=bgpay
spring.datasource.url=jdbc:postgresql://mstrdb.bichilglobus.mn:5432/bichilglobus?currentSchema=bgpay
#----------------------
#Other configuration
#----------------------
cross.origin.max.age=1800000
spring.jpa.open-in-view=false
server.error.include-message=always
qpay.loan.acc=2100102981121020004
qpay.loan.digital.acc=2100102981121020018
qpay.td.acc=2100102981121020016
qpay.dan.acc=2100102982707060047
qpay.loan.acc=999911210202000001
# Digital loan limit 300 collect acc
qpay.digital.collect.acc=9999999902707060001
# qpay dotood dans
qpay.loan.digital.acc=9999999901121020005
# qpay Lising dotood dans
qpay.cont.lising.acc=2109107001120030003
qpay.td.acc=999911210202000001
qpay.dan.acc=9999999902707060002
qpay.collect.acc=2100102982707060044
# Lising loan limit 300 collect acc
qpay.lising.collect.acc=2109107002290000001
cgw.loan.allowance.acc=999911210202000001
cgw.digitalloan.allowance.acc=9999999901121020004
ca.prodcode=2101009999
cgw.loan.allowance.acc=2100102981121020015
cgw.digitalloan.allowance.acc=2100102981121020017
ca.prodcode=2101002100
